### PR TITLE
Added "What's new in AppKit"

### PR DESCRIPTION
**Pull request by mackuba**
First note from the new batch 🙂

### CODE REVIEW

**Comment by zntfdr** [comment]
Whohoo! Thank you Kuba! I'm so excited for shortcuts on macOS 🚀

This year I've added the possibility to add more metadata/external links for authors in their bio, you can see [Michael's profile](https://github.com/FiveStarsBlog/WWDCNotes/blob/main/content/community/abadikaka.md) for all the new metadata, here's the outcome:
Screen Shot 2021-06-11 at 22 54 44


if it's ok for you, I'd like to update your Twitter and website URLs to the new format 😊

Or, if you prefer, you can do this at the next PR. No rush 😄

**Comment by mackuba** [comment]
Ok, PR sent: https://github.com/FiveStarsBlog/WWDCNotes/pull/144

**Comment by mackuba** [comment]
BTW, I was thinking if it wouldn't make sense to show the "originally posted at" line (if present) with some customized style, with a larger margin, so that it doesn't look like it's a quote that's a part of the last subsection? I don't know, something like this (one-minute design):

Screen Shot 2021-06-11 at 20 02 47

vs.

Screen Shot 2021-06-11 at 20 03 49

Or with the link icon from the profile card or some kind of arrow instead of the vertical line. It could be even set as a property in the header instead of just thrown at the end of the body text, if we want to make it really "properly"…

**Comment by zntfdr** [comment]
I can't believe I didn't think of that before, this will be WWDC Notes next feature! Thank you 😃

Do you have any suggestions on the property header name?

Maybe something like: 

```markdown
---
contributors: ...
originUrl: ...
---
...
```
🤔

**Comment by mackuba** [comment]
originalUrl? (or URL, there are different schools 😉)

**Comment by zntfdr** [comment]
Perfect, thank you! I will make it case-insensitive haha

**Pull request merged**
