### PR TITLE
Add wwdc18 session "Building Faster in Xcode"

### PR DESCRIPTION
**Pull request by rogerluan**
I've read [https://github.com/FiveStarsBlog/WWDCNotes/blob/main/CONTRIBUTING.md](CONTRIBUTING.md) ✅ 

Eye-opening session! I recommend watching if you have the spare time.

### CODE REVIEW

**Comment by zntfdr** [comment]
Hi Roger, thank you so much! This is an awesome session 👏🏻

[Your note is now live](https://wwdcnotes.com/notes/wwdc18/408/), welcome to the community ❤️

Also, TIL about `<kbd></kbd>` where was this tag my whole life 🙈

**Comment by rogerluan** [comment]
Haha sweet! Thank you!

Yeah I love `<kbd>`, and it took me awhile to remember it by heart in the beginning but now I always think it of it like an abbreviation for "keyboard" 😉 

By the way, in the website it's looking like this:

image

Perhaps it'd be interesting to come up with a more distinct css visualization for these tags 😊

**Comment by zntfdr** [comment]
Yes, you're right! Thank you for the suggestion, here's the updated style 😊

| Screen Shot 2021-08-29 at 14 46 06 | Screen Shot 2021-08-29 at 14 45 55 |
| --- | --- |

PS
The browser will probably need a couple of refreshes before it fetches the new css!

**Comment by rogerluan** [comment]
Oh wow now _that's_ a quick turnaround 🌟 

I see it live in the website already, and it looks great! Thanks @zntfdr! 🚀

**Pull request merged**
